openapi: 3.0.2
servers:
  - url: http://127.0.0.1:3000
info:
  description: This is API Doc for Angular+ NodeJS Bulletinboard
  title: Swagger API Doc for Gigger
  version: 1.0.0

tags:
  - name: Authentication
    description: Operations about Authentication
  - name: Interests
    description: Operations about Interests
  - name: Events
    description: Operations about Events

paths:
  # Auth Routes
  /api/login:
    post:
      tags:
        - Authentication
      summary: Logs user into the system
      requestBody:
        description: Login User into the system
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "user1"
                password:
                  type: string
                  format: password
                  example: "password123"
          application/xml:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user1"
                password:
                  type: string
                  format: password
                  example: "password123"
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user1"
                password:
                  type: string
                  format: password
                  example: "password123"
      responses:
        "200":
          description: Login Successfully.

  /api/logout:
    post:
      tags:
        - Authentication
      summary: Logs out current logged in user session
      description: ""
      operationId: logoutUser
      parameters: []
      responses:
        default:
          description: Logout Successfully.

  /api/signup:
    post:
      tags:
        - Authentication
      summary: Sign Up
      requestBody:
        description: Signup user into the system
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "user1"
                email:
                  type: string
                  example: "user1@gmail.com"
                password:
                  type: string
                  format: password
                  example: "password123"
                role:
                  type: number
                  format: number
                  example: 1
                dob:
                  type: string
                  example: "11-02-2004"
                interest:
                  type: json
                  example: [1, 2]
      responses:
        "200":
          description: Signup user Successfully.

  # Interest Routes
  /api/interests:
    get:
      tags:
        - Interests
      summary: Get all interests
      description: This can be used without login user.
      responses:
        "200":
          description: Returns all Interests
        "401":
          $ref: "#/components/responses/UnauthorizedError"
 
  # User Routes
  /api/v1/events:
    get:
      tags:
        - Events
      summary: Get all Events
      description: This can only be done by the logged in user.
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: PageNumber 
          schema:
            type: number
        - name: upp
          in: query
          description: Number of users that want to show per Page
          schema:
            type: number
      responses:
        "200":
          description: Returns all Events
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    post:
      tags:
        - Events
      summary: Create Event
      description: This can only be done by the logged in user.
      security:
        - bearerAuth: []
      operationId: createEvent
      requestBody:
        description: Created event
        content:
          application/json:
            schema:
              type: object
              properties:
                eventName:
                  type: string
                  example: "Pink Floyd Live"
                fromTime:
                  type: string
                  example: "8:00 pm"
                toTime:
                  type: string
                  example: "11:00 pm"
                address:
                  type: string
                  example: "Arena di Verona"
                date:
                  type: string
                  example: "20-07-2023"
                description:
                  type: string
                  example: "Preparazione concerto in piazza di sabato"
                participants:
                  type: json
                  example: [1, 2, 3]
                beforeReminder:
                  type: string
                  example: "00:30"
                reminderStatus:
                  type: string
                  example: "busy"
                latitude:
                  type: string
                  example: "1.354092790531372"
                longitude:
                  type: string
                  example: "103.87865454226616"
                artists:
                  type: string
                  example: [1, 2, 3]
                color:
                  type: string
                  example: "#fff"
          application/xml:
            schema:
              type: object
              properties:
                eventName:
                  type: string
                  example: "Pink Floyd Live"
                fromTime:
                  type: string
                  example: "8:00 pm"
                toTime:
                  type: string
                  example: "11:00 pm"
                address:
                  type: string
                  example: "Arena di Verona"
                date:
                  type: string
                  example: "20-07-2023"
                description:
                  type: string
                  example: "Preparazione concerto in piazza di sabato"
                participants:
                  type: json
                  example: [1, 2, 3]
                beforeReminder:
                  type: string
                  example: "00:30"
                reminderStatus:
                  type: string
                  example: "busy"
                latitude:
                  type: string
                  example: "1.354092790531372"
                longitude:
                  type: string
                  example: "103.87865454226616"
                artists:
                  type: string
                  example: [1, 2, 3]
                color:
                  type: string
                  example: "#fff"
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                eventName:
                  type: string
                  example: "Pink Floyd Live"
                fromTime:
                  type: string
                  example: "8:00 pm"
                toTime:
                  type: string
                  example: "11:00 pm"
                address:
                  type: string
                  example: "Arena di Verona"
                date:
                  type: string
                  example: "20-07-2023"
                description:
                  type: string
                  example: "Preparazione concerto in piazza di sabato"
                participants:
                  type: json
                  example: [1, 2, 3]
                beforeReminder:
                  type: string
                  example: "00:30"
                reminderStatus:
                  type: string
                  example: "busy"
                latitude:
                  type: string
                  example: "1.354092790531372"
                longitude:
                  type: string
                  example: "103.87865454226616"
                artists:
                  type: string
                  example: [1, 2, 3]
                color:
                  type: string
                  example: "#fff"
      responses:
        "200":
          description: Created event Successfully.
        "401":
          $ref: "#/components/responses/UnauthorizedError"

components:
  # Schema Usage in component
  # schemas:
  #   Post:
  #     type: object
  #     properties:
  #       title:
  #         type: string
  #         example: "Post01"
  #       description:
  #         type: string
  #         example: "Description01"
  #       status:
  #         type: boolean
  #         example: true
  #       created_user_id:
  #         type: string
  #         example: "62fde243b554f4955fdf7914"
  #     xml:
  #       name: post
  #   User:
  #     type: object
  #     properties:
  #       name:
  #         type: string
  #         example: "Post01"
  #       email:
  #         type: string
  #         example: "Description01"
  #       password:
  #         type: string
  #         format: password
  #         example: "password123"
  #       type:
  #         type: string
  #         description: User Roles
  #         enum:
  #           - Admin
  #           - User
  #       phone:
  #         type: string
  #         example: "0912345678"
  #       dob:
  #         type: string
  #         format: date
  #         example: 2022-06-30
  #       address:
  #         type: string
  #         example: "Address"
  #       profile:
  #         type: string
  #         example: "apiuploads/0fe05c06-2f9d-4056-b80d-ffa37dee7c93_img1.jpg"
  #     xml:
  #       name: user
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid

# 2) Apply the security globally to all operations
security:
  - bearerAuth: []
